# Generated by Django 3.2.16 on 2024-07-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_equipomovimientobodega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipomovimientobodega',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
