# Generated by Django 3.2.16 on 2024-07-29 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0005_auto_20240729_1009'),
        ('inventario', '0003_alter_equipomovimientobodega_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoInstalado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('motivo', models.IntegerField(choices=[(1, 'Instalacion'), (2, 'x Equipo dañado'), (3, 'x upgrade'), (4, 'Otro')], default=1)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
                ('planClienteVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.planclientevivienda')),
            ],
        ),
    ]
