# Generated by Django 3.2.16 on 2024-07-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_equipoinstalado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoinstalado',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Pasivo'), (3, 'otro')], default=1),
        ),
    ]
