# Generated by Django 3.2.16 on 2024-08-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_auto_20240805_0956'),
        ('inventario', '0005_equipoinstalado_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contabilidad.facturaequipo'),
        ),
    ]
