# Generated by Django 3.2.16 on 2024-08-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_auto_20240805_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipomovimientobodega',
            name='condicion',
            field=models.IntegerField(blank=True, choices=[(1, 'Nuevo'), (2, 'Usado'), (3, 'Dañado')], null=True),
        ),
    ]
