# Generated by Django 3.2.16 on 2024-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_equipomovimientobodega_condicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoinstalado',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Usado'), (3, 'Dañado'), (4, 'Revisar')], default=1),
        ),
    ]
