# Generated by Django 3.2.16 on 2024-08-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0020_auto_20240818_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CajaNap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroNap', models.IntegerField()),
                ('nombreNap', models.CharField(blank=True, max_length=300, null=True)),
                ('splitter', models.IntegerField(blank=True, null=True)),
                ('puertos', models.IntegerField(blank=True, null=True)),
                ('puertosDanados', models.IntegerField(default=0)),
                ('potencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=300, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('verificado', models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.barrio')),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Fibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('numeroBuffers', models.IntegerField()),
                ('numeroHilos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('buffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.buffer')),
                ('fibra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.fibra')),
            ],
        ),
        migrations.CreateModel(
            name='Mufa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('splitter', models.IntegerField(blank=True, null=True)),
                ('potencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=300, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('verificado', models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1)),
                ('barrio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.barrio')),
                ('comunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='ODF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuertoODF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto', models.IntegerField()),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('odf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.odf')),
            ],
        ),
        migrations.CreateModel(
            name='PuertoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puerto', models.CharField(max_length=30)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Trazo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoConexion', models.IntegerField(choices=[(1, 'continua mismo hilo sin fusion'), (2, 'fusion a spliter'), (3, 'Fusion con otro hilo de la misma fibra'), (4, 'Fusion con otro hilo de otra fibra'), (5, 'Hilo suelto')], default=1)),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('verificado', models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1)),
                ('hiloSalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiloSalida1', to='fibraOptica.hilo')),
                ('hiloTrazado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiloTrazado1', to='fibraOptica.hilo')),
                ('lleg_Caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.cajanap')),
                ('lleg_Mufa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.mufa')),
            ],
        ),
        migrations.CreateModel(
            name='TrazoPachcord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('verificado', models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1)),
                ('lleg_puertoODF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.puertoodf')),
                ('sal_puertoTarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.puertotarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Trazo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoConexion', models.IntegerField(choices=[(1, 'continua mismo hilo sin fusion'), (2, 'fusion a spliter'), (3, 'Fusion con otro hilo de la misma fibra'), (4, 'Fusion con otro hilo de otra fibra'), (5, 'Hilo suelto')], default=1)),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('verificado', models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1)),
                ('hiloSalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiloSalida2', to='fibraOptica.hilo')),
                ('hiloTrazado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiloTrazado2', to='fibraOptica.hilo')),
                ('lleg_Caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.cajanap')),
                ('lleg_Mufa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.mufa')),
                ('sal_trazo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.trazo1')),
            ],
        ),
        migrations.AddField(
            model_name='trazo1',
            name='sal_trazoPatchcord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.trazopachcord'),
        ),
        migrations.CreateModel(
            name='TarjetaOLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.olt')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('fibra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.fibra')),
            ],
        ),
        migrations.AddField(
            model_name='puertotarjeta',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.tarjetaolt'),
        ),
        migrations.AddField(
            model_name='fibra',
            name='tipoFibra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.tipofibra'),
        ),
        migrations.AddField(
            model_name='cajanap',
            name='mufa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.mufa'),
        ),
    ]
