# Generated by Django 3.2.16 on 2024-08-23 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fibraOptica', '0002_trazo3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trazo4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoConexion', models.IntegerField(choices=[(1, 'continua mismo hilo sin fusion'), (2, 'fusion a spliter'), (3, 'Fusion con otro hilo de la misma fibra'), (4, 'Fusion con otro hilo de otra fibra'), (5, 'Hilo suelto')], default=1)),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('verificado', models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1)),
                ('hiloSalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiloSalida4', to='fibraOptica.hilo')),
                ('hiloTrazado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiloTrazado4', to='fibraOptica.hilo')),
                ('lleg_Caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.cajanap')),
                ('lleg_Mufa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.mufa')),
                ('sal_trazo3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.trazo3')),
            ],
        ),
        migrations.CreateModel(
            name='Trazo5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoConexion', models.IntegerField(choices=[(1, 'continua mismo hilo sin fusion'), (2, 'fusion a spliter'), (3, 'Fusion con otro hilo de la misma fibra'), (4, 'Fusion con otro hilo de otra fibra'), (5, 'Hilo suelto')], default=1)),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('verificado', models.IntegerField(choices=[(1, 'No'), (2, 'Si')], default=1)),
                ('hiloSalida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiloSalida5', to='fibraOptica.hilo')),
                ('hiloTrazado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hiloTrazado5', to='fibraOptica.hilo')),
                ('lleg_Caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.cajanap')),
                ('lleg_Mufa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.mufa')),
                ('sal_trazo4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fibraOptica.trazo4')),
            ],
        ),
    ]
