# Generated by Django 3.2.16 on 2024-09-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fibraOptica', '0003_trazo4_trazo5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazo1',
            name='sal_trazoPatchcord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazo1', to='fibraOptica.trazopachcord'),
        ),
        migrations.AlterField(
            model_name='trazo2',
            name='sal_trazo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazo2', to='fibraOptica.trazo1'),
        ),
        migrations.AlterField(
            model_name='trazo3',
            name='sal_trazo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trazo3', to='fibraOptica.trazo2'),
        ),
        migrations.AlterField(
            model_name='trazopachcord',
            name='sal_puertoTarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patchcors', to='fibraOptica.puertotarjeta'),
        ),
    ]
