# Generated by Django 3.2.16 on 2024-09-13 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infraestructuraFO', '0004_mufa_puerto_olt'),
        ('inventario', '0009_auto_20240821_1649'),
        ('cliente', '0026_planclientevivienda_estadogeneracionpagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AP_nodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ssid', models.CharField(max_length=100)),
                ('frecuencia', models.IntegerField()),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('puerto', models.IntegerField()),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=128)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ap_instalado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipoinstalado')),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('puerto', models.IntegerField()),
                ('usuario', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=128)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('router_instalado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipoinstalado')),
            ],
        ),
        migrations.CreateModel(
            name='Mikrotik_PlanClienteVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('ipv6_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv6')),
                ('puerto', models.IntegerField()),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=128, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.ap_nodos')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infraestructuraFO.cajanap')),
                ('planCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.planclientevivienda')),
            ],
        ),
    ]
