# Generated by Django 3.2.16 on 2024-09-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20240821_1649'),
        ('mikrotik', '0002_ap_nodos_router'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Router',
            new_name='RouterMK',
        ),
    ]
