# Generated by Django 3.2.16 on 2024-09-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_rename_router_routermk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routermk',
            name='contrasena',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='routermk',
            name='puerto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routermk',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
