# Generated by Django 3.2.16 on 2024-09-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0004_auto_20240913_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikrotik_planclientevivienda',
            name='puerto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
