# Generated by Django 3.2.16 on 2024-09-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0005_alter_mikrotik_planclientevivienda_puerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_nodos',
            name='contrasena',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ap_nodos',
            name='puerto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ap_nodos',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apodos', to='mikrotik.routermk'),
        ),
        migrations.AlterField(
            model_name='ap_nodos',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
