# Generated by Django 3.2.16 on 2024-09-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructuraFO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajanap',
            name='nombreNap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cajanap',
            name='numeroNap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
