# Generated by Django 3.2.16 on 2024-09-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0003_rename_router_routermk'),
        ('infraestructuraFO', '0004_mufa_puerto_olt'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='router',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mikrotik.routermk'),
        ),
    ]
