# Generated by Django 3.2.16 on 2024-07-29 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='cliente.ciudad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='digitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nacionalidadCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.nacionalidadcliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.tipocliente'),
        ),
        migrations.AlterField(
            model_name='clientevivienda',
            name='digitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientevivienda',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='cliente.ciudad'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.barrio'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='comunidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.comunidad'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='digitador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
