# Generated by Django 3.2.16 on 2024-07-29 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0002_auto_20240728_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevivienda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteviviendas', to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='clientevivienda',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.vivienda'),
        ),
        migrations.CreateModel(
            name='ClienteViviendaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('clienteVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.clientevivienda')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.vivienda')),
            ],
        ),
    ]
