# Generated by Django 3.2.16 on 2024-08-01 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_ordeninstalacion_tipoinstalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_vivienda/'),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vivienda', to='cliente.barrio'),
        ),
    ]
