# Generated by Django 3.2.16 on 2024-08-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20240731_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planclientevivienda',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspendido'), (3, 'Cortado'), (4, 'CambioPlan')], default=1),
        ),
    ]
