# Generated by Django 3.2.16 on 2024-08-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_planclientevivienda_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planclientevivienda',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspendido'), (3, 'Cortado'), (4, 'CambioPlan'), (5, 'Retirado')], default=1),
        ),
    ]
