# Generated by Django 3.2.16 on 2024-08-13 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_auto_20240805_0956'),
        ('cliente', '0009_alter_planclientevivienda_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('valor_subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_iva', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_abonado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Vencida'), (3, 'Pagada')], default=1)),
                ('dias_extras', models.IntegerField(default=0, help_text='Días extras despues del vencimiento, si no se corta automaticamente')),
                ('ejecucion_dias_extras', models.IntegerField(choices=[(1, 'No Cortar'), (2, 'Cortar')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='planclientevivienda',
            name='estadoEquipos',
            field=models.IntegerField(choices=[(1, 'Funcionando'), (2, 'Por retirar'), (3, 'Retirados'), (4, 'Reseteados por retirados')], default=1),
        ),
        migrations.AddField(
            model_name='planclientevivienda',
            name='estadoServicio',
            field=models.IntegerField(choices=[(1, 'Corriendo'), (2, 'Cortado')], default=1),
        ),
        migrations.AlterField(
            model_name='planclientevivienda',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspendido'), (6, 'Retirado')], default=1),
        ),
        migrations.CreateModel(
            name='PagosPlanClienteVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('valor_abono', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal_abono', models.DecimalField(decimal_places=2, max_digits=8)),
                ('iva_abono', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_abono', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.caja')),
                ('orden_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.ordencobro')),
            ],
        ),
        migrations.AddField(
            model_name='ordencobro',
            name='planClienteVivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.planclientevivienda'),
        ),
    ]
