# Generated by Django 3.2.16 on 2024-08-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0010_auto_20240813_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='alias',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
