# Generated by Django 3.2.16 on 2024-08-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_alter_plan_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencobro',
            name='valor_abonado',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ordencobro',
            name='valor_iva',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordencobro',
            name='valor_subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ordencobro',
            name='valor_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagosplanclientevivienda',
            name='iva_abono',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagosplanclientevivienda',
            name='subtotal_abono',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagosplanclientevivienda',
            name='total_abono',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pagosplanclientevivienda',
            name='valor_abono',
            field=models.FloatField(),
        ),
    ]
