# Generated by Django 3.2.16 on 2024-08-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0013_auto_20240813_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='valor',
            field=models.FloatField(),
        ),
    ]
