# Generated by Django 3.2.16 on 2024-08-14 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0014_alter_plan_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosplanclientevivienda',
            name='valor_abono',
        ),
        migrations.AlterField(
            model_name='pagosplanclientevivienda',
            name='orden_cobro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagosPlanClienteVivienda', to='cliente.ordencobro'),
        ),
    ]
