# Generated by Django 3.2.16 on 2024-08-14 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0015_auto_20240814_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencobro',
            name='fecha_gen_sis',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
