# Generated by Django 3.2.16 on 2024-08-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0016_ordencobro_fecha_gen_sis'),
    ]

    operations = [
        migrations.AddField(
            model_name='planclientevivienda',
            name='fecha_desinstalacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planclientevivienda',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspendido'), (3, 'Retirado'), (4, 'Upgrade')], default=1),
        ),
    ]
