# Generated by Django 3.2.16 on 2024-08-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0018_auto_20240815_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosplanclientevivienda',
            name='tipo_pago',
            field=models.IntegerField(choices=[(1, 'efectivo'), (2, 'transferncia o desposito')], default=1),
        ),
    ]
