# Generated by Django 3.2.16 on 2024-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0019_pagosplanclientevivienda_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_vivienda/'),
        ),
        migrations.AlterField(
            model_name='pagosplanclientevivienda',
            name='tipo_pago',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Transferncia'), (3, 'Deposito')], default=1),
        ),
    ]
