# Generated by Django 3.2.16 on 2024-09-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0020_auto_20240818_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencobro',
            name='mes_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
