# Generated by Django 3.2.16 on 2024-09-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0021_ordencobro_mes_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencobro',
            name='dias_consumo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
