# Generated by Django 3.2.16 on 2024-09-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0023_planclientevivienda_fecha_upgrade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordencobro',
            old_name='mes_pago',
            new_name='mes_pago_servicio',
        ),
    ]
