# Generated by Django 3.2.16 on 2024-09-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0024_rename_mes_pago_ordencobro_mes_pago_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencobro',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.plan'),
        ),
    ]
