# Generated by Django 3.2.16 on 2024-09-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0025_ordencobro_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='planclientevivienda',
            name='estadoGeneracionPagos',
            field=models.IntegerField(choices=[(0, 'No generado'), (1, 'Generado')], default=0),
        ),
    ]
