# Generated by Django 3.2.16 on 2024-09-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0027_cliente_id_viejo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientevivienda',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientevivienda',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Propia'), (2, 'Arrendada'), (3, 'Otro'), (4, 'migracion')], default=1),
        ),
    ]
