# Generated by Django 3.2.16 on 2024-09-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0029_ordeninstalacion_fecha_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordeninstalacion',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
