# Generated by Django 3.2.16 on 2024-10-02 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cliente', '0030_alter_ordeninstalacion_fecha_instalacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoInSitu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticoInSitu', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Intermedio'), (3, 'Grave')], default=1)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoPreliminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticoPreliminar', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Intermedio'), (3, 'Grave')], default=1)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='planclientevivienda',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspendido'), (3, 'Finalizado'), (4, 'Upgrade')], default=1),
        ),
        migrations.CreateModel(
            name='SolucionQuejaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.TextField()),
                ('dificultad', models.IntegerField(choices=[(1, 'Facil'), (2, 'Intermedia'), (3, 'Dificil')], default=1)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudesCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitudCliente', models.TextField()),
                ('dificultad', models.IntegerField(choices=[(1, 'Facil'), (2, 'Intermedia'), (3, 'Dificil')], default=1)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasSolicitudesCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaCliente', models.TextField()),
                ('dificultad', models.IntegerField(choices=[(1, 'Facil'), (2, 'Intermedia'), (3, 'Dificil')], default=1)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuejaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quejaCliente', models.TextField()),
                ('prioridad', models.IntegerField(choices=[(1, 'Leve'), (2, 'Intermedio'), (3, 'Grave')], default=1)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_tentativa', models.DateField(blank=True, null=True)),
                ('aclaracionVisita', models.TextField(blank=True, null=True)),
                ('observacionGeneral', models.TextField(blank=True, null=True)),
                ('otro_QuejaCliente', models.TextField(blank=True, null=True)),
                ('otro_DiagnosticoOficina', models.TextField(blank=True, null=True)),
                ('otro_DiagnosticoInSitu', models.TextField(blank=True, null=True)),
                ('otra_solucion', models.TextField(blank=True, null=True)),
                ('responsalibilad', models.IntegerField(choices=[(1, 'Empresa'), (2, 'Cliente'), (3, 'Otro')], default=1)),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True)),
                ('diagnostico_InSitu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.diagnosticoinsitu')),
                ('diagnostico_preliminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.diagnosticopreliminar')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitadorMantenimiento', to=settings.AUTH_USER_MODEL)),
                ('planClienteVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.planclientevivienda')),
                ('queja_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.quejacliente')),
                ('solucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.solucionquejacliente')),
                ('solucionPreliminar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solucionPreliminar', to='cliente.solucionquejacliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SolucionadorMantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtencionSolicitudesCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_tentativa', models.DateField(blank=True, null=True)),
                ('aclaracionVisita', models.TextField(blank=True, null=True)),
                ('observacionGeneral', models.TextField(blank=True, null=True)),
                ('otro_solicitudes', models.TextField(blank=True, null=True)),
                ('otro_respuesta', models.TextField(blank=True, null=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digitadorSolicitud', to=settings.AUTH_USER_MODEL)),
                ('planClienteVivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.planclientevivienda')),
                ('respuesta_solicitud_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.respuestassolicitudescliente')),
                ('solicitud_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.solicitudescliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solucionadorSolicitud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
