# Generated by Django 3.2.16 on 2024-07-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Diversificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_inversion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_rendimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversionesEmpresa.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SubDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstitucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('diversificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='inversionesEmpresa.diversificacion')),
                ('subDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversionesEmpresa.subdestino')),
            ],
        ),
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inversion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentajeRendimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valorRendimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_caduca', models.DateField()),
                ('estado_diversificacion', models.BooleanField(default=False)),
                ('porcentaje_retiro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_retiro', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_inversion', models.IntegerField(choices=[(1, 'Activa'), (2, 'Pasiva'), (3, 'Retirada')], default=1)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversionesEmpresa.institucion')),
                ('propierario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='institucion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inversionesEmpresa.tipoinstitucion'),
        ),
        migrations.AddField(
            model_name='diversificacion',
            name='inversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diversificaciones', to='inversionesEmpresa.inversion'),
        ),
    ]
