# Generated by Django 3.2.16 on 2024-07-29 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inversionesEmpresa', '0002_alter_diversificacion_inversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diversificacion',
            name='inversion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diversificaciones', to='inversionesEmpresa.inversion'),
        ),
    ]
