# Generated by Django 3.2.16 on 2024-07-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('numeroFactura', models.CharField(max_length=300)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('inventario', models.BooleanField(default=False)),
                ('equiposIngresados', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ModoPagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PagoFacturasEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.caja')),
                ('facturaEquipos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.facturaequipo')),
                ('modoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modopagoproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='facturaequipo',
            name='modoCompra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modocompra'),
        ),
        migrations.AddField(
            model_name='facturaequipo',
            name='presupuesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.presupuesto'),
        ),
        migrations.AddField(
            model_name='facturaequipo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.proveedorequipo'),
        ),
    ]
