# Generated by Django 3.2.16 on 2024-07-30 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0002_alter_facturaequipo_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_pago', models.DateField()),
                ('fecha_emision', models.DateField()),
                ('fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('numeroFactura', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modoCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modocompra')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.presupuesto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.proveedorequipo')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='pagofacturasequipos',
            name='facturaEquipos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='contabilidad.facturaequipo'),
        ),
        migrations.CreateModel(
            name='PagoFacturasServicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.caja')),
                ('facturaServicios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagosServicios', to='contabilidad.facturaservicios')),
                ('modoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modopagoproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='facturaservicios',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.servicio'),
        ),
    ]
