# Generated by Django 3.2.16 on 2024-07-30 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0003_auto_20240730_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasVarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha_emision', models.DateField()),
                ('fecha_limite_pago', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
                ('numeroFactura', models.CharField(blank=True, max_length=300, null=True)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modoCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modocompra')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='VariosF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PagoFacturasVarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.caja')),
                ('facturaVarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagosVarios', to='contabilidad.facturasvarios')),
                ('modoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modopagoproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='facturasvarios',
            name='vario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.variosf'),
        ),
    ]
