# Generated by Django 3.2.16 on 2024-07-30 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0005_auto_20240730_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('valor_dia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaColaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_normales', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dias_extras', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dias_feriados', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valor_dias_normales', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valor_dias_extras', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valor_dias_feriados', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pagado', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.colaboradores')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modopagoproveedor')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.presupuesto')),
            ],
        ),
    ]
