# Generated by Django 3.2.16 on 2024-07-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_colaboradores_planillacolaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planillacolaboradores',
            name='valor_dias_extras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='planillacolaboradores',
            name='valor_dias_feriados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='planillacolaboradores',
            name='valor_dias_normales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='planillacolaboradores',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
