# Generated by Django 3.2.16 on 2024-07-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_auto_20240730_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='planillacolaboradores',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='PagoPlanillaColaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.caja')),
                ('modoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modopagoproveedor')),
                ('planillaColaboradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.planillacolaboradores')),
            ],
        ),
    ]
