# Generated by Django 3.2.16 on 2024-07-30 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_auto_20240730_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoplanillacolaboradores',
            name='planillaColaboradores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagosPlanilla', to='contabilidad.planillacolaboradores'),
        ),
    ]
