# Generated by Django 3.2.16 on 2024-07-30 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contabilidad', '0009_alter_pagoplanillacolaboradores_planillacolaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='valor_comision_cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='colaboradores',
            name='valor_comision_normal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.CreateModel(
            name='PlanillaComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('instalaciones_normales', models.DecimalField(decimal_places=2, max_digits=4)),
                ('instalaciones_cambios', models.DecimalField(decimal_places=2, max_digits=4)),
                ('valor_instalaciones_normales', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('valor_instalaciones_cambio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('valor_total_comisiones', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('abono', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pagado', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.colaboradores')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modopagoproveedor')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='PagoPlanillaComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('observacion', models.CharField(blank=True, max_length=300, null=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.caja')),
                ('modoPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.modopagoproveedor')),
                ('planillaComisiones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagosPlanillaComisiones', to='contabilidad.planillacomisiones')),
            ],
        ),
    ]
