# Generated by Django 3.2.16 on 2024-08-05 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_auto_20240730_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaequipo',
            name='inventario',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagofacturasequipos',
            name='facturaEquipos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagosFacturaEquipos', to='contabilidad.facturaequipo'),
        ),
    ]
