# Generated by Django 3.2.16 on 2024-09-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_auto_20240805_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaservicios',
            name='numeroFactura',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
